#Notes;
#This gen.toml is ready for a davincibox install
#Don't uninstall native firefox pkg cuz of FDM

#Software that does support wayland but needs a flag/etc;
#Wine,LibreSprite,Spotify,Chromium

#Software that doesn't support wayland
#Steam,Proton,krita,FFDEC,Ryujinx,Yuzu,FNF,Resolve

#Packages to be installed via Pacman.
[managers.system]
items = [
    "zip",
    "p7zip",
    "kitty", #THIS IS THE ONLY GOD DAMN TERMINAL THAT JUST "RUNS" SH FILES
    "kio-admin",
    "flatpak-builder",
    "distrobox",
    "lshw",
    "mangohud", #Remove once you learn how to use the flatpak pkg
    "lib32-mangohud", #When not using WoW64 mode of wine (for 32bit win games)
    "gamemode",
    "gamescope",
    "qt6pas", #This is here cuz of the goverlay AppImage
    "timeshift", #Launch with `sudo -E GDK_BACKEND=wayland timeshift-gtk`
    "gnome-disk-utility", #DO NOT REMOVE THIS
    "xdg-desktop-portal-gtk",
    "vkmark",
    "wireguard-tools",
    "headscale",
    "wine",
    "winetricks",
    "kdialog",
    "zenity",
    "htop",
]
#Disabled pkgs

#Packages to be installed via YaY.
[managers.yay]
items = [
    "waydroid",
    "binder_linux-dkms",
    "lact-bin",
]

#Packages to be installed via AM.
[managers.am]
items = [
    "fdm",
    "cromite",
    "fastfetch",
    "gimp-git", #Switch to flatpak once gimp 3 releases
    "goverlay",
    "waydroid-helper",
    "vesktop",
]

#Packages to be installed via AM --user mode.
[managers.am_user]
items = [
    "funkin-legacy", #Using AppImage cuz of wayland support",
    "ultimmc",
]

#Repos to be added system wide.
[managers.flatpak_repos]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "sober https://raw.githubusercontent.com/Twig6943/dotfiles/refs/heads/main/flatpak/repos/sober.flatpakrepo",
]

#Repos to be added as user.
[managers.flatpak_repos_user]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "sober https://raw.githubusercontent.com/Twig6943/dotfiles/refs/heads/main/flatpak/repos/sober.flatpakrepo",
]

#Repos to be added to the extra installation.
[managers.flatpak_repos_extra]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "sober https://raw.githubusercontent.com/Twig6943/dotfiles/refs/heads/main/flatpak/repos/sober.flatpakrepo",
]

# Packages to be installed via Flatpak. (System mode)
[managers.flatpak]
items = [
    "flathub com.dec05eba.gpu_screen_recorder", #I have to install this as system 😭
]

# Packages to be installed via Flatpak. (User mode)
[managers.flatpak_user]
items = [
    "flathub com.github.KRTirtho.Spotube",
    "flathub com.spotify.Client",
    "flathub org.strawberrymusicplayer.strawberry",
    "flathub website.i2pd.i2pd",
    "flathub dev.deedles.Trayscale",
    "flathub flathub com.github.ztefn.haguichi",
    "flathub com.heroicgameslauncher.hgl",
    "flathub org.gnome.Boxes",
    "flathub org.mozilla.firefox",
    "flathub com.google.Chrome", #Fortnite Browser
    "flathub im.nheko.Nheko",
    "flathub im.riot.Riot",
    "flathub io.github.flattool.Warehouse",
    "flathub org.gnome.GHex",
    "flathub org.blender.Blender",
    "flathub rs.ruffle.Ruffle",
    "flathub org.synfig.SynfigStudio",
    "flathub com.github.libresprite.LibreSprite",
    "flathub org.kde.akregator",
    "flathub org.kde.kclock",
    "flathub io.gitlab.adhami3310.Impression",
    "flathub org.kde.filelight",
    "flathub com.rustdesk.RustDesk",
    "flathub com.vscodium.codium",
    "flathub org.libreoffice.LibreOffice",
    "flathub org.nickvision.tubeconverter",
    "flathub in.srev.guiscrcpy",
    "flathub com.obsproject.Studio",
    "flathub org.kde.kdenlive",
    "flathub com.valvesoftware.Steam",
    "flathub org.libretro.RetroArch",
    "flathub net.davidotek.pupgui2",
    "flathub com.github.Matoking.protontricks",
    "flathub org.freedesktop.Platform.VulkanLayer.MangoHud//23.08",
    "flathub org.freedesktop.Platform.VulkanLayer.gamescope//23.08",
    "flathub org.freedesktop.Platform.VulkanLayer.vkBasalt//23.08",
]

# Packages to be installed via Flatpak. (Extra mode)
[managers.flatpak_extra]
items = [
    "flathub io.mrarm.mcpelauncher",
    "flathub sh.ppy.osu",
    "flathub tw.ddnet.ddnet",
    "flathub org.zdoom.GZDoom",
    "flathub net.supertuxkart.SuperTuxKart",
    "flathub dev.bragefuglseth.Keypunch",
    "flathub io.github.TheWisker.Cavasik",
    "flathub com.github.tchx84.Flatseal",
    "flathub io.github.marco_calautti.DeltaPatcher",
    "flathub org.kde.krita",
    "flathub org.inkscape.Inkscape",
    "flathub com.jpexs.decompiler.flash",
    "flathub io.mpv.Mpv",
    "flathub ch.openboard.OpenBoard",
    "flathub io.github.peazip.PeaZip",
    "flathub org.qbittorrent.qBittorrent",
    "flathub org.tenacityaudio.Tenacity",
    "sober org.vinegarhq.Sober",
]

# Packages to be installed as .flatpak files.
#[managers.flatpak_file]
#items = [
    #"github.com/fn2006/PollyMC",
    #"gitgud.io/Twig6943/resolve-flatpak",
#]
